apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: trading-bot
          image: ghcr.io/terabyite/cryptobot-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000