alertmanager:
  enabled: true
  config:
    global:
      smtp_smarthost: ${SMTP_HOST}
      smtp_from: ${ALERT_EMAIL_FROM}
      smtp_auth_username: ${SMTP_USERNAME}
      smtp_auth_password: ${SMTP_PASSWORD}

    route:
      receiver: email-alerts
      routes:
        - matchers:
            - signal!="WAIT"
          receiver: email-alerts

    receivers:
      - name: email-alerts
        email_configs:
          - to: ${ALERT_EMAIL_TO}
            send_resolved: false